language: python
python:
  - "3.6"

# Setup anaconda
env:
  - LD_LIBRARY_PATH=$HOME/.ponytools/lib:$LD_LIBRARY_PATH PATH=$HOME/.ponytools/bin:$HOME/.ponytools/conda/bin:$PATH
install:
  - ./install.py
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install pytest-cov
script:  
  - source $HOME/.ponytools/conda/bin/activate ponytools
  - export PATH=/home/travis/.ponytools/bin/:$PATH
  - which py.test
  - py.test tests/
