#!/usr/bin/env python3
import sys
import MNEcTools.Tools as mn
from optparse import OptionParser


if __name__ == '__main__':
    parser = OptionParser()
    parser.add_option('--geno',default=None,type=str)
    parser.add_option('--annot',default=None,type=str)
    parser.add_option('--samples',default=None,type=str)
    parser.add_option('--ref',default=None,type=str)
    parser.add_option('--out',default=None,type=str)
    options,args = parser.parse_args(sys.argv[1:])

    mn.geno2VCF(options.geno,options.annot,options.samples,options.ref,options.out)
     
